booksnob/critic/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from critic.views import ReviewView
from critic import views

urlpatterns = [
      
    url(r'^review/', views.ReviewView.as_view(), name='review_book'),
    url(r'^thanks/', views.ThanksView.as_view()),
]

booksnob/main/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^critic/', include('critic.urls')),
    url(r'^', include('reader.urls')),
]

booksnob/reader/urls.py
"""main URL Configuration

"""
from django.conf.urls import include, url
from django.contrib import admin

from reader import views



urlpatterns = [
	
	url(r'^home/', views.HomeView.as_view()),
	
]

booksnob/reader/models.py
from django.db import models


class Author(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField()

	def __unicode__(self):
		return '{0} {1}'.format(self.first_name, self.last_name)

class Book(models.Model):
	author = models.ForeignKey(Author)
	name = models.CharField(max_length=100)
	
	def __unicode__(self):
		return '{0} - {1}'.format(self.author, self.name)

booksnob/critic/forms.py
from django import forms
from reader.actions import get_books
from reader.signals import boo

class ReviewForm(forms.Form):
    book_name = forms.ChoiceField(choices=[
    		(book,book) for book in get_books()
    		])
    #CHOICES = (('1','First'),('2','Second'))
    #book_name = forms.ChoiceField(choices =CHOICES)
    text = forms.CharField(widget=forms.Textarea)
       	
    	
    def send_email(self):
    	# send email using the self.cleaned_data dictionary
    	#print (self.cleaned_data)
    	print('Book: {0}'.format(self.cleaned_data['book_name']))
    	print('Messege: {0}'.format(self.cleaned_data['text']))
        print boo

booksnob/critic/views.py
from django.views.generic.edit import FormView
#from django.shortcuts import render
from critic.forms import ReviewForm
from django.views.generic import TemplateView
#from myapp.forms import ContactForm


class ReviewView(FormView):
	template_name = 'critic/review.html'
	form_class = ReviewForm
	success_url = '/critic/thanks/'

	

	def form_valid(self, form):
		form.send_email()
		return super(ReviewView, self).form_valid(form)


class ThanksView(TemplateView):
	template_name ='critic/thanks.html'

booksnob/reader/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

from reader.models import  Author, Book
from reader.actions import get_books,get_author,get_list

class HomeView(TemplateView):
	template_name ='reader/home.html'
	#template_name ='testapp/home2.html'
	#template_name ='testapp/home3.html'
	def get_context_data(self, **kwargs):
		context = super(HomeView, self).get_context_data(**kwargs)

		context['author_name'] = get_author()
			

		context['books'] = get_books()
		context['list'] = get_list()

		return context

booksnob/critic/templates/critic/review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Review</title>
<!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {{form.errors}}
    <h1><center>Welcome!!!</center></h1><hr>
        <form role="form" action="{% url 'review_book' %}" method="post">{% csrf_token %}<center>
            <div class="form-group col-md-4 col-md-offset-4">
                <label  for="id_book_name">Book name:</label>
                <select class="form-control text-center" id="id_book_name" name="book_name">
                {% for val,txt in form.fields.book_name.choices%}
                    <option value="{{val}}">{{txt}}</option>
                {% endfor %}
                </select>
            </div>
            
            <div class="form-group col-xs-12">
                <label for="id_text">Text: </label>
                <textarea id="id_text" name="text" rows=1>{{form.form.text}}</textarea>
                <span class="help-block">This block is to enter information about the book!</span>

            </div>
            
            </div>
            <div class="col-xs-12 ">
            <button type="submit" class="btn btn-primary btn-lg active" value="Send"> Send</button>
            </div>
            </center>
        </form>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> 
</body>
</html>

booksnob/critic/templates/critic/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Thanks</title>
<!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<h1><p class="text-center">Thank you for choice!</p></h1>
<hr>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> 
</body>
</html>

booksnob/reader/templates/reader/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <title>Ok Django!</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    
  </head>
  <body>
  <h1>Authors</h1>
  Hi there!
  {{author_name}}<br><br>
  {{books}}
  <br><br><br>
  <div class="container-fluid">
    <div class="row">
       <div class="col-xs-4">
     <!--  {%for author in author_name %}
       	<p class="bg-primary">{{author}} </p>
        {% endfor %}
        </div>-->
        
     <div class="col-xs-12">
      	<ul class="list-group">
          <!--<li class="list-group-item">{{ book }} </li>-->
      	 {%for author in author_name %}
      			<li class="list-group-item">{{ author }} </li>
      		{% empty %}
      			<li> No books</li>
      		{% endfor %}
      	</ul>
        <ul class="list-group">
          <!--<li class="list-group-item">{{ book }} </li>-->
         
            <li class="list-group-item">{{ book }} </li>
          
            
        </ul>
      </div>
  
    </div>
  </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>